routes/web.php
<?php
use Illuminate\Support\Facades\Route;
Auth::routes();
Auth::id();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('pelanggan', 'PelangganController');
	Route::get('get-diskon-member/{id}', 'PelangganController@get_diskon');
	Route::resource('produk', 'ProdukController');
	Route::post('cek-data-produk', 'ProdukController@cekData')->name('cek-data-produk');
	Route::resource('gudang', 'GudangController');

	// Transaksi Masuk
	Route::resource('transaksi-masuk', 'ProdukMasukController');
	Route::post('transaksi-tambah-produk', 'ProdukMasukController@simpanProduk')->name('transaksi-tambah-produk.store');
	Route::resource('transaksi-list-masuk', 'DetileProdukMasukController');
	
	// Transaksi Penjualan
	Route::resource('transaksi', 'TransaksiController');
	Route::post('simpan-transaksi', 'TransaksiController@simpan_transaksi')->name('simpan_transaksi.store');
	Route::get('transaksi-cetak-nota', 'TransaksiController@cetak_nota');
	Route::resource('transaksi-list', 'DetilePenjualanController');
	Route::get('transaksi-list/{id?}/delete', 'DetilePenjualanController@destroy');
	Route::get('transaksi-hari-ini', 'DetilePenjualanController@index_hari_ini');
	Route::get('cetak-transaksi-hari-ini', 'DetilePenjualanController@cetak_transaksi_hari_ini');
	Route::post('edit-jumlah-detail-transaksi', 'DetilePenjualanController@updateJumlah');

	// Transaksi Pemakaian
	Route::resource('transaksi-pemakaian', 'PemakaianController');
	Route::post('simpan-transaksi-pemakaian', 'PemakaianController@simpan_transaksi')->name('simpan_transaksi_pemakaian.store');
	Route::get('transaksi-pemakaian-cetak-nota', 'PemakaianController@cetak_nota');
	Route::resource('transaksi-pemakaian-list', 'DetailPemakaianController');
	Route::get('transaksi-pemakaian-hari-ini', 'DetailPemakaianController@index_hari_ini');
	Route::get('cetak-transaksi-pemakaian-hari-ini', 'DetailPemakaianController@cetak_transaksi_hari_ini');

	// Transaksi Pengeluaran
	Route::resource('transaksi-pengeluaran', 'PengeluaranController');

	// Transaksi Pre Order
	Route::resource('transaksi-pre-order', 'PreOrderController');

	// Transaksi Retur
	Route::resource('transaksi-retur', 'ReturController');
	Route::get('detil-transaksi-retur/{id}', 'ReturController@detail')->name('transaksi-retur.detail');
	
	// Logistik
	// kartu stok
	Route::get('kartu-stok', 'KartuStokController@kartu_stok')->name('kartu-stok.index');
	Route::post('kartu-stok', 'KartuStokController@kartu_stok_by_index')->name('kartu-stok.index');

	// stok opname
	Route::get('stok-opname', 'StokOpnameController@stok_opname')->name('stok-opname.index');
	Route::post('stok-opname', 'StokOpnameController@stok_opname_by_index')->name('stok-opname.index');
	Route::post('simpan-stok-opname', 'StokOpnameController@store');

	// Penerimaan 
	Route::resource('penerimaan','PenerimaanController');
	// Route::get('detail-penerimaan/{id}/{nomer_masuk}','PenerimaanController@detailBeritaAcara');


	

	// laporan
	Route::prefix('laporan')->group(function () {
		Route::get('transaksi-harian', 'TransaksiController@laporan')->name('laporan.transaksi-harian');
		Route::post('transaksi-harian', 'TransaksiController@laporan_by_waktu')->name('laporan.transaksi-harian');

		Route::get('transaksi-pemakaian-harian', 'PemakaianController@laporan')->name('laporan.transaksi-pemakaian-harian');
		Route::post('transaksi-pemakaian-harian', 'PemakaianController@laporan_by_waktu')->name('laporan.transaksi-pemakaian-harian');

		Route::get('barang', 'ProdukController@laporan')->name('laporan.barang');
		Route::post('barang', 'ProdukController@laporan_by_waktu')->name('laporan.barang');

		Route::get('transaksi-pengeluaran', 'PengeluaranController@laporan')->name('laporan.transaksi-pengeluaran');
		Route::post('transaksi-pengeluaran', 'PengeluaranController@laporan_by_waktu')->name('laporan.transaksi-pengeluaran');

		Route::get('penerimaan', 'PenerimaanController@laporan')->name('laporan.penerimaan');
		Route::post('penerimaan', 'PenerimaanController@laporan_by_tanggal')->name('laporan.penerimaan');

		Route::get('opname', 'StokOpnameController@laporan')->name('laporan.opname');
		Route::post('opname', 'StokOpnameController@laporan_by_tanggal')->name('laporan.opname');

		Route::get('penjualan', 'DetilePenjualanController@laporan')->name('laporan.penjualan');
		Route::post('penjualan', 'DetilePenjualanController@laporan_by_tanggal')->name('laporan.penjualan');

		Route::get('pelanggan', 'PelangganController@laporan')->name('laporan.pelanggan');
		Route::post('pelanggan', 'PelangganController@laporan_by_tanggal')->name('laporan.pelanggan');

		Route::get('barang-masuk', 'DetileProdukMasukController@laporan')->name('laporan.barang-masuk');
		Route::post('barang-masuk', 'DetileProdukMasukController@laporan_by_tanggal')->name('laporan.barang-masuk');
	});

	Route::get('view-import-produk', 'ProdukController@view_import')->name('import.view-import');
	Route::post('template-produk', 'ProdukController@template_import')->name('import.template-produk');
	Route::post('import-produk', 'ProdukController@import')->name('import.produk');

	Route::prefix('verifikasi')->group(function () {
        Route::post('produk', 'ProdukController@data_verifikasi_produk')->name('verifikasi.data-produk');
    });
});

resources/views/master/gudang.blade.php
@extends('template')

@section('title')
Gudang
@endsection

@section('breadcrumb')
<li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
<li class="active">Gudang</li>
@endsection

@section('content')
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">
            Daftar Gudang
            <a class="btn btn-info btn-sm" onclick="tambah()"><i class="fa fa-plus"></i></a>
        </h3>
    </div>
    <div class="box-body">
        <div class="table-responsive">
            <table class="table table-hover table-bordered table-condensed">
                <thead>
                    <tr>
                        <th>Kode</th>
                        <th>Nama</th>
                        <th>Aksi</th>
                    </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="modal fade" id="Modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title"></h4>
            </div>
            <div class="modal-body">
                <form id="form" method="POST" class="form-horizontal">
                    @csrf
                    @method('PUT')
                    <input type="text" name="id" value="" hidden>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Kode</label>
                        <div class="col-sm-9">
                            <input type="text" name="kode" class="form-control">
                            <span class="text-danger kodeError"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-3 control-label">Nama</label>
                        <div class="col-sm-9">
                            <input type="text" name="nama" class="form-control">
                            <span class="text-danger namaError"></span>
                        </div>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default btn-flat" data-dismiss="modal">Keluar</button>
                <button type="button" class="btn btn-primary btn-flat" onclick="save()">Simpan</button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script type="text/javascript">
    //SHOW DATA
    var table;
    table = $('.table').DataTable({
        'language': {
            'url': '/DataTables/datatable-language.json',
        },
        autoWidth: false,
        processing: true,
        serverSide: true,
        ajax: '{{ route('gudang.index') }}',
        columns: [{
            data: 'kode'
        }, {
            data: 'nama'
        }, {
            data: 'aksi',
            searchable: false
        }]
    });

    function tambah() {
        $('#Modal').modal({
            backdrop: 'static',
            keyboard: false,
        })
        $("#form")[0].reset()
        $('input[name="id"]').val()
        $('input[name="_method"]').val('POST')
        $('.modal-title').text('Form Gudang')
    }

    function edit(id) {
        if (confirm('Yakin Edit Data Ini?') == true) {
            $('#Modal').modal({
                backdrop: 'static',
                keyboard: false,
            })
            $("#form")[0].reset()
            $('.modal-title').text('Form Gudang')
            $('input[name="id"]').val(id)
            $('input[name="_method"]').val('PATCH')
            $.get('/gudang/' + id + '/edit', function (resp) {
                $('input[name="kode"]').val(resp.gudang.kode)
                $('input[name="nama"]').val(resp.gudang.nama)
            })
        }
    }


    function save() {
        if (confirm('Yakin Simpan Data Ini?') == true) {
            var data = $('#form').serialize()
            var id = $('input[name="id"]').val()

            if (id == '') {
                var url = '{{ route('gudang.store') }}'
            } else {
                var url = '/gudang/' + id
            }

            $.post(url, data, function (resp) {
                if (resp.sukses == false) {
                    if (resp.error.kode) {
                        $('.kodeError').text(resp.error.kode[0]);
                    }
                    if (resp.error.nama) {
                        $('.namaError').text(resp.error.nama[0]);
                    }
                }
                if (resp.sukses == true) {
                    $('#form')[0].reset();
                    $('#Modal').modal('hide');
                    table.ajax.reload()
                    Swal({
                        position: 'middle',
                        type: 'success',
                        title: resp.message,
                        showConfirmButton: false,
                        timer: 1500
                    })
                }
            })
        }
    }

    function saveForm() {
        var data = $('#formRole').serialize();
        var id = $('input[name="id"]').val();

        $.ajax({
                url: '/gudang/' + id,
                type: 'POST',
                dataType: 'json',
                data: data,
            })
            .done(function (data) {
                if (data.success == true) {
                    $('#formRole')[0].reset()
                    $('#Modal').modal('hide')
                    table.ajax.reload()
                    Swal({
                        position: 'middle',
                        type: 'success',
                        title: data.message,
                        showConfirmButton: false,
                        timer: 1500
                    })
                }
            });

    }
</script>
@endsection

resources/views/master/kategori-edit.blade.php
@extends('template')

@section('title')
  Kategori 
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Kategori</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Kategori
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('kategori.update', $kategori->id) }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ json_encode($sukses)  }}</strong>
                    </div>
                @endif
                @csrf @method('PUT')
                <input type="text" name="id" value="{{ $kategori->id }}" hidden>
                <div class="form-group groupName">
                    <label for="nama" class="col-sm-1 control-label">Nama</label>
                    <div class="col-sm-4">
                        <input type="text" name="nama" class="form-control" value="{{ $kategori->nama }}">
                        <small class="text-danger errorNama"></small>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/kategori-tambah.blade.php
@extends('template')

@section('title')
  Kategori
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Kategori</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Kategori
        	</h3>
		</div>
        <form method="POST" class="form-horizontal" action="{{ route('kategori.store') }}">
            <div class="box-body">
                @if ($sukses = Session::get('gagal'))
                    <div class="alert alert-danger alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ json_encode($sukses->nama)  }}</strong>
                    </div>
                @endif
                @csrf @method('POST')
                <div class="form-group groupName">
                    <label for="nama" class="col-sm-1 control-label">Nama</label>
                    <div class="col-sm-4">
                        <input type="text" name="nama" class="form-control" value="">
                        <small class="text-danger errorNama"></small>
                    </div>
                </div>
            </div>
            <div class="box-footer">
                <button type="submit" class="btn btn-primary btn-flat">Simpan</button>
            </div>
        </form>
	</div>
@endsection

@section('script')
  <script type="text/javascript">
  </script>
@endsection

resources/views/master/kategori.blade.php
@extends('template')

@section('title')
  Kategori <a class="btn btn-default btn-sm btn-flat" href="{{ route('kategori.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Kategori</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Kategori

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>Nama</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
                        @foreach ($kategori as $item)
                            <tr>
                                <th>{{ $item->nama }}</th>
                                <th>
                                    <a type="button" href="{{ route('kategori.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
                                </th>
                            </tr>
                        @endforeach
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/list-transaksi-keluar.blade.php
@extends('template')

@section('title')
  Transaksi Keluar <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi.index') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Keluar</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Transaksi Keluar

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>No Faktur</th>
							<th>Nama Pelanggan</th>
							<th>Jenis Bayar</th>
							<th>Status</th>
							<th>Total Belanja</th>
							<th>Diskon</th>
							<th>Total Bayar</th>
							<th>Total Kembali</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
                        @foreach ($list_transaksi_keluar as $ltk)
                            <tr>
                                <th>{{ $ltk->faktur }}</th>
                                <th>{{ $ltk->nama }}</th>
                                <th>{{ $ltk->jenis_bayar }}</th>
                                <th>{{ $ltk->status }}</th>
                                <th>{{ $ltk->total_belanja }}</th>
                                <th>{{ $ltk->diskon }}</th>
                                <th>{{ $ltk->total_bayar }}</th>
                                <th>{{ $ltk->total_kembali }}</th>
                                <th>
                                    <a type="button" href="{{ route('transaksi-list-keluar.edit', $ltk->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
                                </th>
                            </tr>
                        @endforeach
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/pelanggan.blade.php
@extends('template')

@section('title')
  Pelanggan <a class="btn btn-default btn-sm btn-flat" href="{{ route('pelanggan.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Pelanggan</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Pelanggan

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
                      <thead>
                        <tr>
                          <th>Kode Pelanggan</th>
                          <th>Nama</th>
                          <th>Alamat</th>
                          <th>Email</th>
                          
                          <th>Edit</th>
                          <th>Hapus</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach ($pelanggan as $item)
                            <tr>
                                <th>{{ $item->kode_pelanggan }}</th>
                                <th>{{ $item->nama }}</th>
                                <th>{{ $item->alamat }}</th>
                                <th>{{ $item->email }}</th>
                                
                                <th>
                                    <a type="button" href="{{ route('pelanggan.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a></th>
                                <th>
                                <form method="POST" class="d-inline" onsubmit="return confirm('Yakin dihapus?')"
                                action="{{ route('pelanggan.destroy', $item->id) }}">
                                @csrf
                                <input type="hidden" value="DELETE" name="_method">
                                <input type="submit" value="Hapus" class="btn btn-sm btn-danger btn-flat">
                                </form>
                                </th>
                            </tr>
                        @endforeach
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/periode.blade.php
@extends('template')

@section('title')
  Periode <a class="btn btn-default btn-sm btn-flat" href="{{ route('periode.create') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Periode</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Periode

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>Nama</th>
							<th>Edit</th>
						</tr>
					</thead>
					<tbody>
                        @foreach ($periode as $item)
                            <tr>
                                <th>{{ $item->nama }}</th>
                                <th>
                                    <a type="button" href="{{ route('periode.edit', $item->id) }}" class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
                                </th>
                            </tr>
                        @endforeach
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/master/produk.blade.php
@extends('template')

@section('title')
    Produk <a class="btn btn-default btn-sm btn-flat" href="{{ route('produk.create') }}"><i class="fa fa-plus"></i>
        TAMBAH</a>
@endsection

@section('breadcrumb')
    <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
    <li class="active">produk</li>
@endsection

@section('content')
    <div class="box box-primary">
        <div class="box-header with-border">
            <i class="fa fa-calendar"></i>
            <h3 class="box-title">
                Data produk

            </h3>
        </div>
        <div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered" id="example1">
                    <thead>
                        <tr>
                            <th>Kode</th>
                            <th>Nama Produk</th>
                            <th>Jumlah</th>
                            <th>Harga Beli (Rp.)</th>
                            <th>Harga Jual (Rp.)</th>
                            <th>Harga Grosir (Rp.)</th>
                            <th>Harga Retail (Rp.)</th>
                            <th>Edit</th>
                            <th>Hapus</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($produk as $item)
                            <tr>
                                <th>{{ $item->kode_produk }}</th>
                                <th>{{ $item->nama_produk }}</th>
                                <th>{{ $item->jumlah_stok }}</th>
                                <th>{{ number_format($item->harga) }}</th>
                                <th>{{ number_format($item->harga_jual) }}</th>
                                <th>{{ number_format($item->harga_grosir) }}</th>
                                <th>{{ number_format($item->harga_retail) }}</th>
                                <th>
                                    <a type="button" href="{{ route('produk.edit', $item->id) }}"
                                        class="btn btn-sm btn-primary btn-flat"><i class="fa fa-edit"></i></a>
                                </th>
                                <th>
                                    <form method="POST" class="d-inline" onsubmit="return confirm('Yakin dihapus?')"
                                        action="{{ route('produk.destroy', $item->id) }}">
                                        @csrf
                                        <input type="hidden" value="DELETE" name="_method">
                                        <input type="submit" value="Hapus" class="btn btn-sm btn-danger btn-flat">
                                    </form>
                                </th>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="box-footer">

        </div>
    </div>
@endsection

@section('script')
    <script type="text/javascript">
        //RESET FORM
        function resetForm() {
            $('.groupName').removeClass('has-error')
            $('.errorName').text('')
            $('.groupEmail').removeClass('has-error')
            $('.errorEmail').text('')
            $('.groupPassword').removeClass('has-error')
            $('.errorPassword').text('')
            $('.groupRole').removeClass('has-error')
            $('.errorRole').text('')
        }

        //ADD FORM
        function addForm() {
            resetForm()
            $('#modalUser').modal('show')
            $('.modal-title').text('Tambah User')
            $('#formUser')[0].reset()
            $('input[type="checkbox"]').attr('checked', false);
        }
    </script>
@endsection