routes/web.php
<?php
use Illuminate\Support\Facades\Route;
Auth::routes();
Auth::id();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('pelanggan', 'PelangganController');
	Route::get('get-diskon-member/{id}', 'PelangganController@get_diskon');
	Route::resource('produk', 'ProdukController');
	Route::post('cek-data-produk', 'ProdukController@cekData')->name('cek-data-produk');
	Route::resource('gudang', 'GudangController');

	// Transaksi Masuk
	Route::resource('transaksi-masuk', 'ProdukMasukController');
	Route::post('transaksi-tambah-produk', 'ProdukMasukController@simpanProduk')->name('transaksi-tambah-produk.store');
	Route::resource('transaksi-list-masuk', 'DetileProdukMasukController');
	
	// Transaksi Penjualan
	Route::resource('transaksi', 'TransaksiController');
	Route::post('simpan-transaksi', 'TransaksiController@simpan_transaksi')->name('simpan_transaksi.store');
	Route::get('transaksi-cetak-nota', 'TransaksiController@cetak_nota');
	Route::resource('transaksi-list', 'DetilePenjualanController');
	Route::get('transaksi-list/{id?}/delete', 'DetilePenjualanController@destroy');
	Route::get('transaksi-hari-ini', 'DetilePenjualanController@index_hari_ini');
	Route::get('cetak-transaksi-hari-ini', 'DetilePenjualanController@cetak_transaksi_hari_ini');
	Route::post('edit-jumlah-detail-transaksi', 'DetilePenjualanController@updateJumlah');

	// Transaksi Pemakaian
	Route::resource('transaksi-pemakaian', 'PemakaianController');
	Route::post('simpan-transaksi-pemakaian', 'PemakaianController@simpan_transaksi')->name('simpan_transaksi_pemakaian.store');
	Route::get('transaksi-pemakaian-cetak-nota', 'PemakaianController@cetak_nota');
	Route::resource('transaksi-pemakaian-list', 'DetailPemakaianController');
	Route::get('transaksi-pemakaian-hari-ini', 'DetailPemakaianController@index_hari_ini');
	Route::get('cetak-transaksi-pemakaian-hari-ini', 'DetailPemakaianController@cetak_transaksi_hari_ini');

	// Transaksi Pengeluaran
	Route::resource('transaksi-pengeluaran', 'PengeluaranController');

	// Transaksi Pre Order
	Route::resource('transaksi-pre-order', 'PreOrderController');

	// Transaksi Retur
	Route::resource('transaksi-retur', 'ReturController');
	Route::get('detil-transaksi-retur/{id}', 'ReturController@detail')->name('transaksi-retur.detail');
	
	// Logistik
	// kartu stok
	Route::get('kartu-stok', 'KartuStokController@kartu_stok')->name('kartu-stok.index');
	Route::post('kartu-stok', 'KartuStokController@kartu_stok_by_index')->name('kartu-stok.index');

	// stok opname
	Route::get('stok-opname', 'StokOpnameController@stok_opname')->name('stok-opname.index');
	Route::post('stok-opname', 'StokOpnameController@stok_opname_by_index')->name('stok-opname.index');
	Route::post('simpan-stok-opname', 'StokOpnameController@store');

	// Penerimaan 
	Route::resource('penerimaan','PenerimaanController');
	// Route::get('detail-penerimaan/{id}/{nomer_masuk}','PenerimaanController@detailBeritaAcara');


	

	// laporan
	Route::prefix('laporan')->group(function () {
		Route::get('transaksi-harian', 'TransaksiController@laporan')->name('laporan.transaksi-harian');
		Route::post('transaksi-harian', 'TransaksiController@laporan_by_waktu')->name('laporan.transaksi-harian');

		Route::get('transaksi-pemakaian-harian', 'PemakaianController@laporan')->name('laporan.transaksi-pemakaian-harian');
		Route::post('transaksi-pemakaian-harian', 'PemakaianController@laporan_by_waktu')->name('laporan.transaksi-pemakaian-harian');

		Route::get('barang', 'ProdukController@laporan')->name('laporan.barang');
		Route::post('barang', 'ProdukController@laporan_by_waktu')->name('laporan.barang');

		Route::get('transaksi-pengeluaran', 'PengeluaranController@laporan')->name('laporan.transaksi-pengeluaran');
		Route::post('transaksi-pengeluaran', 'PengeluaranController@laporan_by_waktu')->name('laporan.transaksi-pengeluaran');

		Route::get('penerimaan', 'PenerimaanController@laporan')->name('laporan.penerimaan');
		Route::post('penerimaan', 'PenerimaanController@laporan_by_tanggal')->name('laporan.penerimaan');

		Route::get('opname', 'StokOpnameController@laporan')->name('laporan.opname');
		Route::post('opname', 'StokOpnameController@laporan_by_tanggal')->name('laporan.opname');

		Route::get('penjualan', 'DetilePenjualanController@laporan')->name('laporan.penjualan');
		Route::post('penjualan', 'DetilePenjualanController@laporan_by_tanggal')->name('laporan.penjualan');

		Route::get('pelanggan', 'PelangganController@laporan')->name('laporan.pelanggan');
		Route::post('pelanggan', 'PelangganController@laporan_by_tanggal')->name('laporan.pelanggan');

		Route::get('barang-masuk', 'DetileProdukMasukController@laporan')->name('laporan.barang-masuk');
		Route::post('barang-masuk', 'DetileProdukMasukController@laporan_by_tanggal')->name('laporan.barang-masuk');
	});

	Route::get('view-import-produk', 'ProdukController@view_import')->name('import.view-import');
	Route::post('template-produk', 'ProdukController@template_import')->name('import.template-produk');
	Route::post('import-produk', 'ProdukController@import')->name('import.produk');

	Route::prefix('verifikasi')->group(function () {
        Route::post('produk', 'ProdukController@data_verifikasi_produk')->name('verifikasi.data-produk');
    });
});

app/Penerimaan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Penerimaan extends Model
{
    //
}

app/Http/Controllers/PenerimaanController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\ProdukMasuk;
use App\Penerimaan;
use App\DetileProdukMasuk;
use App\Produk;
use App\Kategori;
use App\KartuStok;
use Session;
use Validator;
use Auth;
use DB;
use PDF;
use Artisan;


class PenerimaanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['list_produk'] = ProdukMasuk::all();
        return view('penerimaan.list-penerimaan', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $cek = Validator::make($request->all(), [
            'nama_produk' => ['unique:penerimaans'],
            'id_kategori' => ['required'],
        ],[
            'nama_produk.unique' => 'Produk Sudah di inputkan !',
            'id_kategori.required' => 'Kategori Wajib di pilih !',
        ]);
        if ($cek->fails()) {
            return response()->json(['sukses' => false, 'error' => $cek->errors()]);
        
        } else { 
            DB::transaction(function () use ($request) {     
            
            $penerimaan = New Penerimaan();  
            $penerimaan->no_masuk        = $request['kode_masuk'];
            $penerimaan->id_produk       = $request['id_produk'];
            $penerimaan->nama_produk     = $request['nama_produk'];
            $penerimaan->id_kategori     = $request['id_kategori'];
            $penerimaan->harga_beli      = rupiah($request['harga_beli']);
            $penerimaan->harga_jual      = rupiah($request['harga_jual']);
            $penerimaan->harga_grosir    = rupiah($request['harga_grosir']);
            $penerimaan->harga_retail    = rupiah($request['harga_retail']);
            $penerimaan->harga_partai    = rupiah($request['harga_partai']);
            $penerimaan->jumlah_masuk    = $request['qty'];
            $penerimaan->tanggal         = $request['tanggal'];
            $penerimaan->id_periode      = $request['id_periode'];
            $penerimaan->tahun           = date('Y');
            $penerimaan->id_user         = Auth::user()->id;
            $penerimaan->status_terima   = 'sudah';
            $penerimaan->save();

            $produk = Produk::where('id', $request['id_produk'])->first();
            $produk->kode_produk = $request['kode_produk'];
            $produk->id_kategori = $request['id_kategori'];
            $produk->nama_produk = $request['nama_produk'];
            $produk->jumlah_stok = $request['qty'];
            $produk->tanggal_masuk = $request['tanggal'];
            $produk->ukuran = '-';
            $produk->harga = $request['harga_beli'];
            $produk->harga_jual = $request['harga_jual'];
            $produk->harga_grosir = $request['harga_grosir'];
            $produk->harga_retail = $request['harga_retail'];
            $produk->harga_partai = $request['harga_partai'];
            $produk->laba = 0 ;
            $produk->update();

            $kartu = New KartuStok();
            $kartu->id_periode = $request['id_periode'];
            $kartu->tahun = date('Y');
            $kartu->id_produk = $request['id_produk'];
            $kartu->masuk = $request['jumlah_masuk'];
            $kartu->keluar = 0 ;
            $kartu->total = 0 ;
            $kartu->keterangan = 'Penerimaan dengan kode masuk =>'.$request['kode_masuk'].'';
            $kartu->id_user = Auth::user()->id;
            $kartu->save();

            $detile = DetileProdukMasuk::where('id_produk' , $request['id_produk'])->first();
            $detile->status_terima = 'sudah';
            $detile->update();

            

            
            });
            return response()->json(['sukses' => true]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        // return $id; die;
        $data['produk_masuk'] = ProdukMasuk::where('no_masuk',$id)->get();
        $data['detail'] = DetileProdukMasuk::where('no_masuk', $id)->get();
        $data['total_masuk'] = DetileProdukMasuk::where('no_masuk', $id)->sum('jumlah_masuk');
        $data['kategori'] = Kategori::all();
        // return $data; die;
        return view('penerimaan.detile-list-penerimaan', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $detail = DetileProdukMasuk::find($id);
        return response()->json(['detail' => $detail]);
    }

    public function detailBeritaAcara($id , $nomer_masuk)
    {
        $detail = DetileProdukMasuk::find($id);
        return response()->json(['detail' => $detail]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function laporan()
    {
        $data['penerimaan'] = Penerimaan::where('created_at', 'LIKE', date('Y-m-d') . '%')->get();

        return view('laporan.logistik.laporan-penerimaan', $data)->with('no', 1);
    }

    public function laporan_by_tanggal(Request $request)
    {
        request()->validate(['tgl_awal' => 'required', 'tgl_akhir' => 'required'], ['tgl_awal.required' => 'Harap Diisi, Jagan Dilewati!', 'tgl_akhir.required' => 'Harap Diisi, Jagan Dilewati!']);

        $awal  = $request['tgl_awal'];
        $akhir = $request['tgl_akhir'];

        $data['penerimaan'] = Penerimaan::whereBetween('created_at', [date('' . $awal . ' 00:00:00'), date('' . $akhir . ' 23:59:00')])
        ->latest()
        ->get();

        if ($request['lanjut']) {
            // return [date('' . $awal . ' 00:00:00'), date('' . $akhir . ' 23:59:00')]; die;
            // return $data; die;
            return view('laporan.logistik.laporan-penerimaan', $data)->with('no', 1);
        } elseif ($request['pdf']) {
            $no = 1;
            $pdf = PDF::loadView('laporan.logistik.pdf-laporan-penerimaan', $data);
            $pdf->setPaper('A4', 'potret');
            return $pdf->stream();
        } elseif ($request['excel']) {
            return Excel::download(new TabunganExport($awal,$akhir), 'laporan harian.xlsx');
        }
    }



}

resources/views/penerimaan/detile-list-penerimaan.blade.php
@extends('template')

@section('title')
  Transaksi Masuk <a class="btn btn-default btn-sm btn-flat" href="{{ route('penerimaan.index') }}"><i class="fa fa-list"></i> List Penerimaan</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Masuk</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            List data Penerimaan
            </h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>No masuk</th>
							<th>Tanggal Masuk</th>
							<th>Creator</th>
                            <th>List Barang</th>
							
						</tr>
					</thead>
					<tbody>
                        @isset($produk_masuk)
                            @foreach($produk_masuk as $produks)
                                <tr>
                                    <th>{{ $produks->no_masuk }}</th>
                                    <th>{{ $produks->tanggal }}</th>
                                    <th>{{ baca_user($produks->id_user)}}</th>
                                    <th><select name="list" class="form-control" onchange="pilih()">
                                            <option value="">Pilih Barang</option>
                                        @foreach ($detail as $item )
                                            <option value="{{ $item->id }}"> {{ $item->nama_produk }}
                                            </option>
                                        @endforeach
                                        </select>
                                        <br>
                                        <span class="text-danger NamaError"></span>
                                    </th>
                                </tr>
                            @endforeach
                        @endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer"> <hr>
            <div class="TampilDetile hide">
                <form id="form" method="POST" class="form-horizontal tampil">
                            @csrf  @method('POST')
                        
                            <div class="col-sm-3" hidden>
                                <div>
                                    <label>id Produk</label>
                                    <input type="text" name="id_produk" class="form-control" value="" readonly>
                                </div>
                            </div>
                            <div class="col-sm-3" hidden>
                                <div>
                                    <label>kode Produk</label>
                                    <input type="text" name="kode_produk" class="form-control" value="" readonly>
                                </div>
                            </div>

                        <div class="row">
                            <div class="col-sm-3">
                                <div>
                                    <label>Nama Produk</label>
                                    <input type="text" name="nama_produk" class="form-control" value="" readonly>
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div>
                                    <label>Kategori</label>
                                    <select name="id_kategori" class="form-control" required>
                                        <option value="">Pilih</option>
                                        @foreach ($kategori as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                        @endforeach
                                    </select>
                                    <span class="text-danger KategoriError"></span>
                                </div>
                            </div>
                        

                            <div class="col-sm-3">
                                <div>
                                    <label>Jumlah</label>
                                    <input type="text" name="qty" class="form-control" value="" readonly>
                                </div>
                            </div>

                            <div class="col-sm-3" hidden>
                                <div>
                                    <label>Jumlah masuk</label>
                                    <input type="text" name="jumlah_masuk" class="form-control" value="" readonly>
                                </div>
                            </div>
                        

                            <div class="col-sm-3">
                                <div>
                                    <label>Tanggal</label>
                                    @foreach ($produk_masuk as $item)
                                    <input type="date" name="tanggal" class="form-control" value="{{ $item->tanggal }}" readonly>
                                    @endforeach
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-sm-3">
                                <div>
                                    <label>Harga Beli</label>
                                    <input type="text" name="harga_beli" class="form-control" value=0 > 
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div>
                                    <label>Harga Jual</label>
                                    <input type="text" name="harga_jual" class="form-control" value=0 > 
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div>
                                    <label>Harga Grosir</label>
                                    <input type="text" name="harga_grosir" class="form-control" value=0>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div>
                                    <label>Harga Retail</label>
                                    <input type="text" name="harga_retail" class="form-control" value=0>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-sm-3" >
                                <div>
                                    <label>Harga Partai</label>
                                    <input type="text" name="harga_partai" class="form-control" value=0>
                                </div>
                            </div>
                            <div class="col-sm-3" hidden>
                                <div>
                                    <label>id_periode</label>
                                @foreach ($produk_masuk as $item)
                                    <input type="text" name="id_periode" class="form-control" value={{ $item->id_periode }}>                                    
                                @endforeach
                                </div>
                            </div>
                            <div class="col-sm-3" hidden>
                                <div>
                                    <label>kode masuk</label>
                                @foreach ($produk_masuk as $item)
                                    <input type="text" name="kode_masuk" class="form-control" value={{ $item->no_masuk }}>                                    
                                @endforeach
                                </div>
                            </div>
                        </div>
                    

                        <div class="row">
                            <div class="col-sm-3" id="tombol">
                                <div>
                                    <label class="col-sm-12"><br></label>
                                    <button type="button" class="btn btn-info btn-flat" onclick="save()">Tambah</button>
                                </div>
                            </div>
                        </div>
                    </form>
            </div>
		</div>
	</div>


@endsection

@section('script')
<script type="text/javascript">
    function pilih() {
            var pilihan = $('select[name="list"]').val()
            if(pilihan == ''){
                $('.TampilDetile').addClass('hide');
                $('.NamaError').addClass('hide');
            }else{
                $('.TampilDetile').removeClass('hide');
                $('.NamaError').removeClass('hide');
                $.get('/penerimaan/' + pilihan + '/edit', function (resp) {
                $('input[name="nama_produk"]').val(resp.detail.nama_produk)
                $('input[name="qty"]').val(resp.detail.jumlah_masuk)
                $('input[name="id_produk"]').val(resp.detail.id_produk)
                $('input[name="kode_produk"]').val(resp.detail.kode_produk)
                $('input[name="jumlah_masuk"]').val(resp.detail.jumlah_masuk)
            })
            }
            
        }

    function save() {
        if (confirm('Yakin Simpan Data Ini?') == true) {
            var data = $('#form').serialize()
                var url = '{{ route('penerimaan.store') }}'
            $.post(url, data, function (resp) {
                if (resp.sukses == false) {
                    if (resp.error.nama_produk) {
                        $('.NamaError').text(resp.error.nama_produk[0]);
                    }
                    if (resp.error.id_kategori) {
                        $('.KategoriError').text(resp.error.id_kategori[0]);
                    }
                }
                if (resp.sukses == true) {
                    $('#form')[0].reset();
                    Swal({
                        position: 'middle',
                        type: 'success',
                        title: resp.message,
                        showConfirmButton: true,
                    })
                    location.reload();
                }
            })
        }
        
    }

</script>
@endsection

resources/views/penerimaan/list-penerimaan.blade.php
@extends('template')

@section('title')
  Transaksi Masuk <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-masuk.index') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Masuk</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Penerimaan

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered" id="example1">
					<thead>
						<tr>
							<th>No Masuk</th>
							<th>Tanggal</th>
							<th>Jumlah</th>
							<th>Keterangan</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>
                        @foreach ($list_produk as $item)
                            <tr>
                                <th>{{ $item->no_masuk }}</th>
                                <th>{{ $item->tanggal }}</th>
                                <th>{{ $item->jumlah_masuk }}</th>
                                <th>{{ $item->keterangan}}</th>
                                <th>
                                    <a type="button" href="{{ route('penerimaan.show', $item->no_masuk) }}" class="btn btn-sm btn-info btn-flat"><i class="fa fa-paper-plane"></i></fa-solid></a>
                                </th>
                            </tr>
                        @endforeach
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection