routes/web.php
<?php
use Illuminate\Support\Facades\Route;
Auth::routes();
Auth::id();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('pelanggan', 'PelangganController');
	Route::get('get-diskon-member/{id}', 'PelangganController@get_diskon');
	Route::resource('produk', 'ProdukController');
	Route::post('cek-data-produk', 'ProdukController@cekData')->name('cek-data-produk');
	Route::resource('gudang', 'GudangController');

	// Transaksi Masuk
	Route::resource('transaksi-masuk', 'ProdukMasukController');
	Route::post('transaksi-tambah-produk', 'ProdukMasukController@simpanProduk')->name('transaksi-tambah-produk.store');
	Route::resource('transaksi-list-masuk', 'DetileProdukMasukController');
	
	// Transaksi Penjualan
	Route::resource('transaksi', 'TransaksiController');
	Route::post('simpan-transaksi', 'TransaksiController@simpan_transaksi')->name('simpan_transaksi.store');
	Route::get('transaksi-cetak-nota', 'TransaksiController@cetak_nota');
	Route::resource('transaksi-list', 'DetilePenjualanController');
	Route::get('transaksi-list/{id?}/delete', 'DetilePenjualanController@destroy');
	Route::get('transaksi-hari-ini', 'DetilePenjualanController@index_hari_ini');
	Route::get('cetak-transaksi-hari-ini', 'DetilePenjualanController@cetak_transaksi_hari_ini');
	Route::post('edit-jumlah-detail-transaksi', 'DetilePenjualanController@updateJumlah');

	// Transaksi Pemakaian
	Route::resource('transaksi-pemakaian', 'PemakaianController');
	Route::post('simpan-transaksi-pemakaian', 'PemakaianController@simpan_transaksi')->name('simpan_transaksi_pemakaian.store');
	Route::get('transaksi-pemakaian-cetak-nota', 'PemakaianController@cetak_nota');
	Route::resource('transaksi-pemakaian-list', 'DetailPemakaianController');
	Route::get('transaksi-pemakaian-hari-ini', 'DetailPemakaianController@index_hari_ini');
	Route::get('cetak-transaksi-pemakaian-hari-ini', 'DetailPemakaianController@cetak_transaksi_hari_ini');

	// Transaksi Pengeluaran
	Route::resource('transaksi-pengeluaran', 'PengeluaranController');

	// Transaksi Pre Order
	Route::resource('transaksi-pre-order', 'PreOrderController');

	// Transaksi Retur
	Route::resource('transaksi-retur', 'ReturController');
	Route::get('detil-transaksi-retur/{id}', 'ReturController@detail')->name('transaksi-retur.detail');
	
	// Logistik
	// kartu stok
	Route::get('kartu-stok', 'KartuStokController@kartu_stok')->name('kartu-stok.index');
	Route::post('kartu-stok', 'KartuStokController@kartu_stok_by_index')->name('kartu-stok.index');

	// stok opname
	Route::get('stok-opname', 'StokOpnameController@stok_opname')->name('stok-opname.index');
	Route::post('stok-opname', 'StokOpnameController@stok_opname_by_index')->name('stok-opname.index');
	Route::post('simpan-stok-opname', 'StokOpnameController@store');

	// Penerimaan 
	Route::resource('penerimaan','PenerimaanController');
	// Route::get('detail-penerimaan/{id}/{nomer_masuk}','PenerimaanController@detailBeritaAcara');


	

	// laporan
	Route::prefix('laporan')->group(function () {
		Route::get('transaksi-harian', 'TransaksiController@laporan')->name('laporan.transaksi-harian');
		Route::post('transaksi-harian', 'TransaksiController@laporan_by_waktu')->name('laporan.transaksi-harian');

		Route::get('transaksi-pemakaian-harian', 'PemakaianController@laporan')->name('laporan.transaksi-pemakaian-harian');
		Route::post('transaksi-pemakaian-harian', 'PemakaianController@laporan_by_waktu')->name('laporan.transaksi-pemakaian-harian');

		Route::get('barang', 'ProdukController@laporan')->name('laporan.barang');
		Route::post('barang', 'ProdukController@laporan_by_waktu')->name('laporan.barang');

		Route::get('transaksi-pengeluaran', 'PengeluaranController@laporan')->name('laporan.transaksi-pengeluaran');
		Route::post('transaksi-pengeluaran', 'PengeluaranController@laporan_by_waktu')->name('laporan.transaksi-pengeluaran');

		Route::get('penerimaan', 'PenerimaanController@laporan')->name('laporan.penerimaan');
		Route::post('penerimaan', 'PenerimaanController@laporan_by_tanggal')->name('laporan.penerimaan');

		Route::get('opname', 'StokOpnameController@laporan')->name('laporan.opname');
		Route::post('opname', 'StokOpnameController@laporan_by_tanggal')->name('laporan.opname');

		Route::get('penjualan', 'DetilePenjualanController@laporan')->name('laporan.penjualan');
		Route::post('penjualan', 'DetilePenjualanController@laporan_by_tanggal')->name('laporan.penjualan');

		Route::get('pelanggan', 'PelangganController@laporan')->name('laporan.pelanggan');
		Route::post('pelanggan', 'PelangganController@laporan_by_tanggal')->name('laporan.pelanggan');

		Route::get('barang-masuk', 'DetileProdukMasukController@laporan')->name('laporan.barang-masuk');
		Route::post('barang-masuk', 'DetileProdukMasukController@laporan_by_tanggal')->name('laporan.barang-masuk');
	});

	Route::get('view-import-produk', 'ProdukController@view_import')->name('import.view-import');
	Route::post('template-produk', 'ProdukController@template_import')->name('import.template-produk');
	Route::post('import-produk', 'ProdukController@import')->name('import.produk');

	Route::prefix('verifikasi')->group(function () {
        Route::post('produk', 'ProdukController@data_verifikasi_produk')->name('verifikasi.data-produk');
    });
});

app/Penjualan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Penjualan extends Model
{
    //
}

resources/views/penjualan/detail-pre-order.blade.php
@extends('template')

@section('title')
  Detail Transaksi Pre Order <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-pre-order.index') }}"><i class="fa fa-list"></i> Daftar Transaksi Pre Order</a>
@endsection

@section('breadcrumb')
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
                Detail Pre Order
        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <table class="table table-hover table-condensed table-bordered" style="width: 50%">
					<thead class="bg-warning">
						<tr>
							<th>Kode Pre Order :</th>
                            <th>{{ $list_transaksi->nama }}</th>
							<th>User :</th> 
                            <th>{{ baca_user($list_transaksi->user_id) }}</th>
                        </tr>
					</thead>
				</table>
                <hr>
                <table class="table table-hover table-condensed" style="width: 100%">
					<thead class="bg-info">
						<tr>
							<th>Nama Barang</th>
                            <th>{{ $list_transaksi->nama }}</th>
                            <th rowspan="5" style="vertical-align:top">Keterangan :<br>{{ $list_transaksi->keterangan }}</th>
                        </tr>
                        <tr>
							<th>Kategori</th> 
                            <th>{{ baca_kategori($list_transaksi->id_kategori) }}</th>
                        </tr>
                        <tr>
							<th>Harga</th>
                            <th>{{ $list_transaksi->harga }}</th>
                        </tr>
                        <tr>
							<th>Warna</th> 
                            <th>{{ $list_transaksi->warna }}</th>
                        </tr>
                        <tr>
							<th>Ukuran</th> 
                            <th>{{ $list_transaksi->ukuran }}</th>
                        </tr>
					</thead>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/penjualan/detail-retur.blade.php
@extends('template')

@section('title')
  Transaksi Detail Retur <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-retur.index') }}"><i class="fa fa-list"></i> Daftar Transaksi Retur</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Detail Retur</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Transaksi Retur
        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <div class="col-md-7">
                    <table class="table table-hover table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th>Kode Produk</th>
                                <th>Nama Produk</th>
                                <th>Jumlah</th>
                            </tr>
                        </thead>
                        <tbody>
                            @isset($detail)
                                @foreach($detail as $item)
                                    <tr>
                                        <th>{{ baca_produk($item->id_produk)->kode_produk }}</th>
                                        <th>{{ $item->nama_produk }}</th>
                                        <th>{{ number_format($item->jumlah) }}</th>
                                    </tr>
                                @endforeach
                            @endisset
                        </tbody>
                    </table>
                </div>
                <div class="col-md-5">
                    <table class="table table-hover table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th>Tanggal :</th>
                                <th>{{ $retur->tanggal }}</th>
                                <th>Kode Retur :</th>
                                <th>{{ $retur->kode_retur }}</th>
                            </tr>
                            <tr>
                                <th>Pelanggan :</th>
                                <th>{{ baca_pelanggan($retur->id_pelanggan) }}</th>
                                <th>User :</th>
                                <th>{{ baca_user($retur->user_id) }}</th>
                            </tr>
                            <tr>
                                <th colspan="4">Keterangan : {{ $retur->keterangan }}</th>
                            </tr>
                        </thead>
                    </table>
                </div>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/penjualan/detail-transaksi.blade.php
@extends('template')

@section('title')
  Transaksi Detail Penjualan <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-list.index') }}"><i class="fa fa-list"></i> Daftar Transaksi Penjualan</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Detail Penjualan</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <table class="table table-hover">
					<thead>
						<tr class="bg-primary">
							<th>Faktur</th>
                            <th>Pelanggan</th>
                            <th>Kasir</th>
						</tr>
                        <tr class="bg-info">
							<th>{{ $penjualan->faktur }}</th>
							<th>{{ baca_pelanggan($penjualan->id_pelanggan) }}</th>
                            <th>{{ baca_user($penjualan->user_id) }}</th>
						</tr>
					</thead>
				</table>
                <hr>
                <table class="table table-hover">
					<thead class="bg-primary">
						<tr>
							<th>Kode Produk</th>
							<th>Nama Produk</th>
                            <th>Harga Produk</th>
							<th>Jumlah</th>
                            <th>Sub Total</th>
						</tr>
					</thead>
					<tbody class="bg-info">
                        @isset($detail)
                            @foreach($detail as $item)
                                <tr>
                                    <th>{{ baca_produk($item->id_produk)->kode_produk }}</th>
                                    <th>{{ baca_produk($item->id_produk)->nama_produk }}</th>
                                    <td>{{ number_format($item->harga) }}</td>
                                    <th>{{ number_format($item->jumlah) }}</th>
                                    <th>{{ number_format($item->sub_total ) }}</th>
                                </tr>
                            @endforeach
                        @endisset
					</tbody>
                    <tfoot>
                        <tr>
                            <th colspan="4" class="text-right">Total</th>
                            <th>{{ number_format($total_penjualan) }}</th>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-right">Total Diskon</th>
                            <th>{{ number_format($penjualan->diskon) }}</th>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-right">Total Bayar</th>
                            <th>{{ number_format($penjualan->total_bayar) }}</th>
                        </tr>
                        <tr>
                            <th colspan="4" class="text-right">Total Kembali</th>
                            <th><u>{{ number_format($penjualan->total_kembali) }}</u></th>
                        </tr>
                    </tfoot>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/penjualan/list-pre-order.blade.php
@extends('template')

@section('title')
  Transaksi Daftar Pre Order
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Pre Order</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
                Data Transaksi Pre Order
        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <table class="table table-hover table-condensed table-bordered" id="example1">
					<thead>
						<tr>
							<th>Kode Pre Order</th>
							<th>Nama Pelanggan</th>
							<th>Nama Barang</th>
							<th>Ukuran</th>
							<th>Warna</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>
						@isset($list_transaksi)
							@foreach ($list_transaksi as $item)
								<tr>
									<th>{{ $item->kode_pre_order }}</th>
									<th>{{ baca_pelanggan($item->id_pelanggan) }}</th>
									<th>{{ $item->nama }}</th>
									<th>{{ $item->ukuran }}</th>
                                    <th>{{ $item->warna }}</th>
									<th>
										<a type="button" href="{{ route('transaksi-pre-order.show', $item->id) }}" class="btn btn-sm btn-info btn-flat"><i class="fa fa-eye"></i></a>
									</th>
								</tr>
							@endforeach
						@endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/penjualan/list-transaksi.blade.php
@extends('template')

@section('title')
  Transaksi Daftar Penjualan
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Penjualan</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Transaksi Penjualan

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered" id="example1">
					<thead>
						<tr>
							<th>No Faktur</th>
							<th>Nama Pelanggan</th>
							<th>Status</th>
							<th>Total Belanja</th>
							<th>Diskon</th>
							<th>Status Retur</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>
						@isset($list_transaksi)
							@foreach ($list_transaksi as $item)
								<tr>
									<th>{{ $item->faktur }}</th>
									<th>{{ baca_pelanggan($item->id_pelanggan) }}</th>
									<th>{{ $item->status }}</th>
									<th>{{ number_format($item->total_belanja) }}</th>
									<th>{{ number_format($item->diskon) }}</th>
									<th class="text-center">
										@if (baca_retur_count($item->faktur) > 0)
											<span class="pull-center-container">
												<small class="label pull-center bg-green">Ada Retur</small>
											</span>
										@else
										<span class="pull-center-container">
											<small class="label pull-center bg-red">Tidak Ada Retur</small>
										</span>
										@endif
									</th>
									<th>
										<a type="button" href="{{ route('transaksi-list.show', $item->faktur) }}" class="btn btn-sm btn-info btn-flat"><i class="fa fa-eye"></i></a>
										@if (baca_retur_count($item->faktur) > 0)
											<span class="pull-center-container">
												<small class="label pull-center bg-green">Ada Retur</small>
											</span>
											<a type="button" href="{{ route('transaksi-retur.detail', baca_retur($item->faktur)->kode_retur) }}" class="btn btn-sm btn-info btn-flat"><i class="fa fa-eye"> Detail Retur</i></a>
										@else
											<a type="button" href="{{ route('transaksi-retur.show', $item->faktur) }}" class="btn btn-sm btn-warning btn-flat"><i class="fa fa-edit"></i>Retur</a>
										@endif
									</th>
								</tr>
							@endforeach
						@endisset
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/penjualan/pre-order.blade.php
@extends('template')

@section('title')
  Transaksi Pre Order
@endsection

@section('breadcrumb')
 
@endsection

@section('content')
<section class="content container-fluid">
    <div class="box box-default">
        <div class="box-body">
            @if ($sukses = Session::get('sukses'))
                <div class="alert alert-success alert-block">
                    <button type="button" class="close" data-dismiss="alert">×</button>
                    <strong>{{ json_encode($sukses)  }}</strong>
                </div>
            @endif
            <form method="POST" class="form-horizontal" action="{{ route('transaksi-pre-order.store') }}">
                @csrf @method('POST')
                <div class="col-md-7">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-12">Nama Pelanggan</label>
                                <select class="form-control select2" name="id_pelanggan" required>
                                    <option value="">Cari Pelanggan</option>
                                    @isset($pelanggan)
                                        @foreach ($pelanggan as $item)
                                            <option value="{{ $item->id }}">{{ $item->nama }} || Kode : {{ $item->kode_pelanggan }}</option>
                                        @endforeach
                                    @endisset
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-sm-12">Nama Kategori</label>
                            <select class="form-control select2" name="id_kategori" required>
                                <option value="">Cari Kategori</option>
                                @isset($kategori)
                                    @foreach ($kategori as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                    @endforeach
                                @endisset
                            </select>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-12">Nama</label>
                                <input type="text" class="form-control" name="nama" style="line-height: normal;" required>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-sm-12">Warna</label>
                            <input type="text" class="form-control" name="warna" style="line-height: normal;" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label class="col-sm-12">Ukuran</label>
                                <select name="ukuran" class="form-control" required>
                                    <option value="">Pilih</option>
                                    <option value="S">S</option>
                                    <option value="M">M</option>
                                    <option value="L">L</option>
                                    <option value="XL">XL</option>
                                    <option value="XXL">XXL</option>
                                    <option value="XXXL">XXXL</option>
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <label class="col-sm-12">Harga</label>
                            <input type="text" class="form-control uang" name="harga" style="line-height: normal;" required>
                        </div>
                    </div>
                </div>
                <div class="col-md-5">
                    <div class="row">
                        <div class="col-sm-12">
                            <label class="col-sm-10">Keterangan</label>
                            <textarea name="keterangan" class="form-control" cols="30" rows="10" required></textarea>
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="margin">
                                <div class="btn-group">
                                <button type="submit" class="btn btn-success">Simpan</button>
                                </div>
                                <div class="btn-group">
                                <button type="submit" class="btn btn-danger">Batal</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('script')
  <script type="text/javascript">
    
  </script>
@endsection

resources/views/penjualan/retur.blade.php
@extends('template')

@section('title')
  Transaksi Retur <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-list.index') }}"><i class="fa fa-list"></i> Daftar Transaksi Penjualan</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Retur</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Transaksi Penjualan
        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <form method="POST" class="form-horizontal" action="{{ route('transaksi-retur.store') }}">
                    @csrf @method('POST')
                    <table class="table table-hover table-condensed table-bordered" style="width: 50%;">
                        <thead>
                            <tr>
                                <th>Faktur : </th>
                                <th>
                                    {{ $penjualan->faktur }}
                                    <input type="hidden" name="faktur" class="form-control" value="{{ $penjualan->faktur }}">
                                </th>
                                <th>Kasir :</th>
                                <th>{{ baca_user($penjualan->user_id) }}</th>
                            </tr>
                        </thead>
                    </table>
                    <div class="col-md-7">
                        <table class="table table-hover table-condensed table-bordered">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" value="1" id="select-all"></th>
                                    <th>Kode Produk</th>
                                    <th>Nama Produk</th>
                                    <th>Harga Produk</th>
                                    <th>Jumlah</th>
                                </tr>
                            </thead>
                            <tbody>
                                @isset($detail)
                                    @foreach($detail as $item)
                                        <tr>
                                            <th><input type='checkbox' name='id_produk[]' value='{{ $item->id_produk }}' required></th>
                                            <th>{{ baca_produk($item->id_produk)->kode_produk }}</th>
                                            <th>{{ baca_produk($item->id_produk)->nama_produk }}</th>
                                            <td>{{ number_format($item->harga) }}</td>
                                            <th>
                                                <input type="number" name="jumlah" class="form-control" min="{{ number_format($item->jumlah) }}" max="{{ number_format($item->jumlah) }}" value="{{ number_format($item->jumlah) }}">
                                            </th>
                                        </tr>
                                    @endforeach
                                @endisset
                            </tbody>
                        </table>
                    </div>
                    <div class="col-md-5">
                        <div class="row">
                            <div class="col-sm-6">
                                <label class="col-sm-12">Jenis Retur</label>
                                <select class="form-control select2" name="jenis_retur" required>
                                    <option value="">Cari Jenis Retur</option>
                                    <option value="tunai">Tunai</option>
                                    <option value="tukar">Tukar</option>
                                </select>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-6">
                                <label class="col-sm-12">Nama Pelanggan</label>
                                <select class="form-control select2" name="id_pelanggan">
                                    <option value="">Cari Pelanggan</option>
                                    @foreach ($pelanggan as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }} || Kode : {{ $item->kode_pelanggan }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-sm-6">
                                <label class="col-sm-12">Tanggal</label>
                                <input type="date" class="form-control" name="tanggal" style="line-height: normal;" required>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <label class="col-sm-10">Keterangan</label>
                                <textarea name="keterangan" class="form-control" cols="30" rows="10"></textarea>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-sm-12">
                                <div class="margin">
                                    <div class="btn-group">
                                    <button type="submit" class="btn btn-success">Simpan</button>
                                    </div>
                                    <div class="btn-group">
                                    <button type="reset" class="btn btn-danger">Batal</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    $('#select-all').click(function(){
      $('input[type="checkbox"]').prop('checked', this.checked);
    });
  </script>
@endsection