routes/web.php
<?php
use Illuminate\Support\Facades\Route;
Auth::routes();
Auth::id();

Route::group(['middleware' => 'auth'], function () {
	Route::get('/', 'HomeController@index');
	Route::get('/home', 'HomeController@index')->name('home');

	Route::resource('user', 'UserController')->except(['create', 'show', 'destroy']);
	Route::get('user-data', 'UserController@datalist')->name('user-data');
	Route::get('getRole', 'UserController@getRole')->name('getRole');

	Route::resource('role', 'RoleController')->except(['create', 'store', 'show', 'destroy']);
	Route::get('role-data', 'RoleController@datalist')->name('role-data');

	Route::resource('periode', 'PeriodeController');
	Route::resource('kategori', 'KategoriController');
	Route::resource('pelanggan', 'PelangganController');
	Route::get('get-diskon-member/{id}', 'PelangganController@get_diskon');
	Route::resource('produk', 'ProdukController');
	Route::post('cek-data-produk', 'ProdukController@cekData')->name('cek-data-produk');
	Route::resource('gudang', 'GudangController');

	// Transaksi Masuk
	Route::resource('transaksi-masuk', 'ProdukMasukController');
	Route::post('transaksi-tambah-produk', 'ProdukMasukController@simpanProduk')->name('transaksi-tambah-produk.store');
	Route::resource('transaksi-list-masuk', 'DetileProdukMasukController');
	
	// Transaksi Penjualan
	Route::resource('transaksi', 'TransaksiController');
	Route::post('simpan-transaksi', 'TransaksiController@simpan_transaksi')->name('simpan_transaksi.store');
	Route::get('transaksi-cetak-nota', 'TransaksiController@cetak_nota');
	Route::resource('transaksi-list', 'DetilePenjualanController');
	Route::get('transaksi-list/{id?}/delete', 'DetilePenjualanController@destroy');
	Route::get('transaksi-hari-ini', 'DetilePenjualanController@index_hari_ini');
	Route::get('cetak-transaksi-hari-ini', 'DetilePenjualanController@cetak_transaksi_hari_ini');
	Route::post('edit-jumlah-detail-transaksi', 'DetilePenjualanController@updateJumlah');

	// Transaksi Pemakaian
	Route::resource('transaksi-pemakaian', 'PemakaianController');
	Route::post('simpan-transaksi-pemakaian', 'PemakaianController@simpan_transaksi')->name('simpan_transaksi_pemakaian.store');
	Route::get('transaksi-pemakaian-cetak-nota', 'PemakaianController@cetak_nota');
	Route::resource('transaksi-pemakaian-list', 'DetailPemakaianController');
	Route::get('transaksi-pemakaian-hari-ini', 'DetailPemakaianController@index_hari_ini');
	Route::get('cetak-transaksi-pemakaian-hari-ini', 'DetailPemakaianController@cetak_transaksi_hari_ini');

	// Transaksi Pengeluaran
	Route::resource('transaksi-pengeluaran', 'PengeluaranController');

	// Transaksi Pre Order
	Route::resource('transaksi-pre-order', 'PreOrderController');

	// Transaksi Retur
	Route::resource('transaksi-retur', 'ReturController');
	Route::get('detil-transaksi-retur/{id}', 'ReturController@detail')->name('transaksi-retur.detail');
	
	// Logistik
	// kartu stok
	Route::get('kartu-stok', 'KartuStokController@kartu_stok')->name('kartu-stok.index');
	Route::post('kartu-stok', 'KartuStokController@kartu_stok_by_index')->name('kartu-stok.index');

	// stok opname
	Route::get('stok-opname', 'StokOpnameController@stok_opname')->name('stok-opname.index');
	Route::post('stok-opname', 'StokOpnameController@stok_opname_by_index')->name('stok-opname.index');
	Route::post('simpan-stok-opname', 'StokOpnameController@store');

	// Penerimaan 
	Route::resource('penerimaan','PenerimaanController');
	// Route::get('detail-penerimaan/{id}/{nomer_masuk}','PenerimaanController@detailBeritaAcara');


	

	// laporan
	Route::prefix('laporan')->group(function () {
		Route::get('transaksi-harian', 'TransaksiController@laporan')->name('laporan.transaksi-harian');
		Route::post('transaksi-harian', 'TransaksiController@laporan_by_waktu')->name('laporan.transaksi-harian');

		Route::get('transaksi-pemakaian-harian', 'PemakaianController@laporan')->name('laporan.transaksi-pemakaian-harian');
		Route::post('transaksi-pemakaian-harian', 'PemakaianController@laporan_by_waktu')->name('laporan.transaksi-pemakaian-harian');

		Route::get('barang', 'ProdukController@laporan')->name('laporan.barang');
		Route::post('barang', 'ProdukController@laporan_by_waktu')->name('laporan.barang');

		Route::get('transaksi-pengeluaran', 'PengeluaranController@laporan')->name('laporan.transaksi-pengeluaran');
		Route::post('transaksi-pengeluaran', 'PengeluaranController@laporan_by_waktu')->name('laporan.transaksi-pengeluaran');

		Route::get('penerimaan', 'PenerimaanController@laporan')->name('laporan.penerimaan');
		Route::post('penerimaan', 'PenerimaanController@laporan_by_tanggal')->name('laporan.penerimaan');

		Route::get('opname', 'StokOpnameController@laporan')->name('laporan.opname');
		Route::post('opname', 'StokOpnameController@laporan_by_tanggal')->name('laporan.opname');

		Route::get('penjualan', 'DetilePenjualanController@laporan')->name('laporan.penjualan');
		Route::post('penjualan', 'DetilePenjualanController@laporan_by_tanggal')->name('laporan.penjualan');

		Route::get('pelanggan', 'PelangganController@laporan')->name('laporan.pelanggan');
		Route::post('pelanggan', 'PelangganController@laporan_by_tanggal')->name('laporan.pelanggan');

		Route::get('barang-masuk', 'DetileProdukMasukController@laporan')->name('laporan.barang-masuk');
		Route::post('barang-masuk', 'DetileProdukMasukController@laporan_by_tanggal')->name('laporan.barang-masuk');
	});

	Route::get('view-import-produk', 'ProdukController@view_import')->name('import.view-import');
	Route::post('template-produk', 'ProdukController@template_import')->name('import.template-produk');
	Route::post('import-produk', 'ProdukController@import')->name('import.produk');

	Route::prefix('verifikasi')->group(function () {
        Route::post('produk', 'ProdukController@data_verifikasi_produk')->name('verifikasi.data-produk');
    });
});

resources/views/logistik/detail-transaksi-masuk.blade.php
@extends('template')

@section('title')
  Transaksi Masuk <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-list-masuk.index') }}"><i class="fa fa-list"></i> Daftar Produk Masuk</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Masuk</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Transaksi Masuk    
        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                <table class="table table-hover table-condensed table-bordered">
					<thead>
						<tr>
							<th>Kode Produk</th>
							<th>Nama Produk</th>
							<th>Jumlah Barang Masuk</th>
							
						</tr>
					</thead>
					<tbody>
                        @isset($detail)
                            @foreach($detail as $item)
                                <tr>
                                    <th>{{ $item->kode_produk }}</th>
                                    <th>{{ $item->nama_produk }}</th>
                                    <th>{{ $item->jumlah_masuk }}</th>
                                </tr>
                            @endforeach
                        @endisset
					</tbody>
                    <tfoot>
                        <tr>
                            <th colspan="2" class="text-right">Total</th>
                            <th>{{ number_format($total_masuk) }}</th>
                        </tr>
                    </tfoot>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">

  </script>
@endsection

resources/views/logistik/kartu-stok.blade.php
@extends('template')

@section('title')
  Transaksi Kartu Stok
@endsection

@section('breadcrumb')
 
@endsection

@section('content')
<section class="content container-fluid">
    <div class="box box-default">
        <div class="box-body">
            <div class="col-md-12">
                <form method="POST" class="form-horizontal" action="{{ url('kartu-stok') }}">
                    @csrf @method('POST')
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label>Nama Produk</label>
                                <select class="form-control select2" name="id_produk" required>
                                    @if (isset($produk))
                                       <option value="">Cari Produk</option>
                                        @foreach ($produk as $item)
                                            @if (isset($_POST['id_produk']) && $_POST['id_produk'] == $item->id)
                                                <option value="{{ $item->id }}" selected="true">{{ $item->nama_produk }}</option>
                                            @else
                                                <option value="{{ $item->id }}">{{ $item->nama_produk }}</option>
                                            @endif
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                        </div>
                        <div class="col-sm-3">
                            <label>Periode</label>
                            <select class="form-control select2" name="id_periode" required>
                                <option value="">Cari Periode</option>
                                @if (isset($periode))
                                    @foreach ($periode as $item)
                                        @if (empty($_POST['id_periode']) && date('m') == $item->id)
                                            <option value="{{ $item->id }}" selected="true">{{ $item->nama }}</option>
                                        @elseif(isset($_POST['id_periode']) && $_POST['id_periode'] == $item->id)
                                            <option value="{{ $item->id }}" selected="true">{{ $item->nama }}</option>
                                        @else
                                            <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                        @endif
                                    @endforeach
                                @endif
                            </select>
                        </div>
                        <div class="col-sm-3">
                            <label class="col-sm-12">&nbsp;&nbsp;</label>
                            <input type="submit" name="lanjut" class="btn btn-info btn-flat" value="TAMPIL">
                            <input type="submit" name="pdf" class="btn btn-warning btn-flat" value="PDF">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="box box-default">
        <div class="box-header with-border">
            <h3 class="box-title">Daftar Kartu Stok</h3>
        </div>
        <div class="box-body">
            <div class="col-md-12">
                <table class="table table-condensed">
                    <thead>
                        <tr>
                            <th>
                                Kode Produk
                            </th>
                            <th>
                                Nama Produk
                            </th>
                            <th>
                                Masuk
                            </th>
                            <th>
                                Keluar
                            </th>
                            <th>
                                Total
                            </th>
                            <th>
                                keterangan
                            </th>
                            <th>
                                Periode
                            </th>
                            <th>
                                Tahun
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @isset($kartu_stok)
                            @foreach ($kartu_stok as $item)
                                <tr>
                                    <th>
                                        {{ baca_produk($item->id_produk)->kode_produk }}
                                    </th>
                                    <th>
                                        {{ baca_produk($item->id_produk)->nama_produk }}
                                    </th>
                                    <th>
                                        {{ number_format($item->masuk) }}
                                    </th>
                                    <th>
                                        {{ number_format($item->keluar) }}
                                    </th>
                                    <th>
                                        {{ number_format($item->total) }}
                                    </th>
                                    <th>
                                        {{ $item->keterangan }}
                                    </th>
                                    <th>
                                        {{ baca_periode( $item->id_periode) }}
                                    </th>
                                    <th>
                                        {{ $item->tahun }}
                                    </th>
                                </tr>
                            @endforeach
                        @endisset
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('script')
  <script type="text/javascript">
  </script>
@endsection

resources/views/logistik/list-transaksi-masuk.blade.php
@extends('template')

@section('title')
  Transaksi Masuk <a class="btn btn-default btn-sm btn-flat" href="{{ route('transaksi-masuk.index') }}"><i class="fa fa-plus"></i> TAMBAH</a>
@endsection

@section('breadcrumb')
  <li><a href="{{ url('/') }}"><i class="fa fa-dashboard"></i> Home</a></li>
  <li class="active">Transaksi Masuk</li>
@endsection

@section('content')
	<div class="box box-primary">
		<div class="box-header with-border">
			<i class="fa fa-calendar"></i>
            <h3 class="box-title">
            Data Transaksi Masuk

        	</h3>
		</div>
		<div class="box-body">
            <div class="table-responsive">
                @if ($sukses = Session::get('sukses'))
                    <div class="alert alert-success alert-block">
                        <button type="button" class="close" data-dismiss="alert">×</button>
                        <strong>{{ $sukses }}</strong>
                    </div>
                @endif
                <table class="table table-hover table-condensed table-bordered" id="example1">
					<thead>
						<tr>
							<th>No Masuk</th>
							<th>Tanggal</th>
							<th>Jumlah</th>
							<th>Keterangan</th>
							<th>Aksi</th>
						</tr>
					</thead>
					<tbody>
                        @foreach ($list_transaksi_masuk as $item)
                            <tr>
                                <th>{{ $item->no_masuk }}</th>
                                <th>{{ $item->tanggal }}</th>
                                <th>{{ $item->jumlah_masuk }}</th>
                                <th>{{ $item->keterangan}}</th>
                                <th>
                                    <a type="button" href="{{ route('transaksi-list-masuk.show', $item->no_masuk) }}" class="btn btn-sm btn-info btn-flat"><i class="fa fa-eye"></i></a>
                                </th>
                            </tr>
                        @endforeach
					</tbody>
				</table>
			</div>
		</div>
		<div class="box-footer">

		</div>
	</div>

@endsection

@section('script')
  <script type="text/javascript">
    //RESET FORM
    function resetForm() {
    	$('.groupName').removeClass('has-error')
		$('.errorName').text('')
		$('.groupEmail').removeClass('has-error')
		$('.errorEmail').text('')
		$('.groupPassword').removeClass('has-error')
		$('.errorPassword').text('')
		$('.groupRole').removeClass('has-error')
		$('.errorRole').text('')
    }

    //ADD FORM
    function addForm() {
    	resetForm()
    	$('#modalUser').modal('show')
    	$('.modal-title').text('Tambah User')
    	$('#formUser')[0].reset()
    	$('input[type="checkbox"]').attr('checked', false);
    }

  </script>
@endsection

resources/views/logistik/transaksi-produk-masuk.blade.php
@extends('template')

@section('title')
  Transaksi Produk Masuk
@endsection

@section('breadcrumb')
 
@endsection

@section('content')
{{-- bawah --}}
<section class="content container-fluid">
    <div class="box box-default">
        <div class="box-body">
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <label>Pilih Jenis Produk</label>
                        <select name="pilihTransaksi" class="form-control" onchange="pilih()">
                            <option value="">Pilih Jenis Produk</option>
                            <option value="lama">lama</option>
                            <option value="baru">baru</option>
                        </select>
                    </div>
                </div>
            </div>

            {{-- lama --}}
            <div class="row">
                <div class="col-sm-12">
                    <form method="POST" class="form-horizontal hide lama" action="{{ route('transaksi-list-masuk.store') }}">
                        @csrf @method('POST')
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <label>Nama Produk</label>
                                    <select class="form-control select2" name="produk_id" required style="width: 100%">
                                        <option value="">Cari Produk</option>
                                        @foreach ($produk as $item)
                                            <option value="{{ $item->id }}">{{ $item->nama_produk }} || QTY : {{ $item->jumlah_stok }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <div>
                                    <label>Jumlah</label>
                                    <input type="number" name="qty" value="1" class="form-control" required>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <label class="col-sm-12"><br></label>
                                <button type="submit" class="btn btn-info btn-flat">TAMBAH</button>
                            </div>
                    </form>
                </div>
            </div>

            {{-- baru  --}}
            <div class="row">
                <div class="col-sm-12">
                    <form id="form" method="POST" class="form-horizontal hide baru">
                            @csrf  @method('POST')                          
                            <div class="col-sm-3">
                                <div class="form-group">
                                    <label>Nama Produk</label>
                                    <input type="text" name="nama_produk" class="form-control" value="">
                                    <span class="text-danger namaError"></span>
                                    <br>
                                    <div class="hide data-produk-lama">
                                    </div>
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div>
                                    <label>Kategori</label>
                                    <select name="id_kategori" class="form-control" required>
                                        <option value="">Pilih</option>
                                        @foreach ($kategori as $item)
                                        <option value="{{ $item->id }}">{{ $item->nama }}</option>
                                        @endforeach
                                    </select>
                                    <span class="text-danger kategoriError"></span>
                                </div>
                            </div>

                            <div class="col-sm-3">
                                <div>
                                    <label>Jumlah</label>
                                    <input type="number" name="qty" class="form-control" value="">
                                    <span class="text-danger jumlahError"></span>
                                </div>
                            </div>

                            <div class="form-group" hidden>
                                <label class="col-sm-3 control-label">Harga Beli</label>
                                <div class="col-sm-9">
                                    <input type="text" name="harga" class="form-control uang" value=0 > 
                                </div>
                            </div>
                            <div class="form-group" hidden>
                                <label class="col-sm-3 control-label">Harga ecer</label>
                                <div class="col-sm-9">
                                    <input type="text" name="harga_ecer" class="form-control uang" value=0>
                                </div>
                            </div>
                            <div class="form-group" hidden>
                                <label class="col-sm-3 control-label">Harga Grosir</label>
                                <div class="col-sm-9">
                                    <input type="text" name="harga_grosir" class="form-control uang" value=0>
                                </div>
                            </div>
                            <div class="form-group" hidden>
                                <label class="col-sm-3 control-label">Harga reseller</label>
                                <div class="col-sm-9">
                                    <input type="text" name="harga_reseller" class="form-control uang" value=0>
                                </div>
                            </div>
                            <div class="form-group" hidden>
                                <label class="col-sm-3 control-label">Harga Partai</label>
                                <div class="col-sm-9">
                                    <input type="text" name="harga_partai" class="form-control uang" value=0>
                                </div>
                            </div>
                            <div class="col-sm-3">
                                <label class="col-sm-12"><br></label>
                                <button type="button" class="btn btn-info btn-flat" onclick="save()">Tambah</button>
                            </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <div class="box box-default">
        <div class="box-body">
            <div class="col-md-7">
                <table class="table table-borderless">
                    <caption><b>Daftar Belanja</b></caption>
                    <thead>
                        <tr>
                            <th>
                                Kode Produk
                            </th>
                            <th>
                                Nama Produk
                            </th>
                            <th>
                                Jumlah
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @isset($detailmasuk)
                            @foreach ($detailmasuk as $item)
                                <tr>
                                    <th>
                                        {{ baca_produk($item->id_produk)->kode_produk }}
                                    </th>
                                    <th>
                                        {{ baca_produk($item->id_produk)->nama_produk }}
                                    </th>
                                    <th>
                                        {{  number_format($item->jumlah_masuk) }}
                                    </th>
                                </tr>
                            @endforeach
                        @endisset
                    </tbody>
                </table>
            </div>
            <div class="col-md-5">
                <form method="POST" class="form-horizontal" action="{{ route('transaksi-masuk.store') }}">
                    @csrf @method('POST')
                    <div class="row">
                        <div class="col-sm-6">
                            <label class="col-sm-12">Tanggal</label>
                            <input type="date" class="form-control" name="tanggal" style="line-height: normal;" required>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <label class="col-sm-10">Keterangan</label>
                            <textarea name="keterangan" class="form-control" cols="30" rows="10" required></textarea>
                        </div>
                        
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="margin">
                                <div class="btn-group">
                                <button type="submit" class="btn btn-success">Simpan</button>
                                </div>
                                <div class="btn-group">
                                <button type="submit" class="btn btn-danger">Batal</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    {{-- Modal --}}
    
@endsection

@section('script')
  <script type="text/javascript">
    jQuery(document).ready(function() {
        $('.uang').maskNumber({
            thousands: ".",
            integer: true,
        });
        $('.baru').addClass('hide');
        $('.lama').addClass('hide');

        $('input[name="nama_produk"]').keyup(function(){ 
	        var query = $(this).val();
	        if(query != '')
	        {
                var _token = $('input[name="_token"]').val();
                $.ajax({
                    url:"{{ route('cek-data-produk') }}",
                method:"POST",
                data:{query:query, _token:_token},
                success:function(data){
                    $('.data-produk-lama').removeClass('hide');
                    $('.data-produk-lama').fadeIn();  
                    $('.data-produk-lama').html(data);
                }
                });
	        }
	    });
	    $(document).on('click', 'li', function(){  
	        // $('input[name="nama_produk"]').val($(this).text());  
	        $('.data-produk-lama').fadeOut();  
	    }); 
    });

    function tambah() {
        $('#Modal').modal({
            backdrop: 'static',
            keyboard: false,
        })
        $("#form")[0].reset()
        $('input[name="id"]').val()
        $('input[name="_method"]').val('POST')

    }

    function save() {
        if (confirm('Yakin Simpan Data Ini?') == true) {
            var data = $('#form').serialize()
                var url = '{{ route('transaksi-tambah-produk.store') }}'
            $.post(url, data, function (resp) {
                if (resp.sukses == false) {
                    if (resp.error.nama_produk) {
                        $('.namaError').text(resp.error.nama_produk[0]);
                    }
                    if (resp.error.id_kategori) {
                        $('.kategoriError').text(resp.error.id_kategori[0]);
                    }
                    if (resp.error.jumlah_stok) {
                        $('.jumlahError').text(resp.error.jumlah_stok[0]);
                    }
                }
                if (resp.sukses == true) {
                    $('#form')[0].reset();
                    $('#Modal').modal('hide');
                    Swal({
                        position: 'middle',
                        type: 'success',
                        title: resp.message,
                        showConfirmButton: false,
                        timer: 1500
                    })
                    $('select[name="pilihTransaksi"]').val('');
                    location.reload()
                }
            })
        }
    }
    
    function ribuan(x) {
        return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ".");
    }

    function hitung(){
        var total_diskon    = $('input[name="diskon"]').val();
		var total_belanja   = $('input[name="total_belanja"]').val();
        var total_bayar     = $('input[name="total_bayar"]').val();
		var belanja         = parseInt(total_belanja.split('.').join("") );
        var bayar           = parseInt(total_bayar.split('.').join("") );
        var diskon          = parseInt(total_diskon.split('.').join("") );
		var total    	    = belanja - diskon;
        var total_semua     = bayar - total;
		$('input[name="total_kembali"]').val(ribuan(total_semua));
	}

    function pilih() {
            var pilihan = $('select[name="pilihTransaksi"]').val()
            
            if(pilihan == 'lama'){
                $('.baru').addClass('hide');
                $('.lama').removeClass('hide');
            }else if (pilihan == 'baru'){
                $('.baru').removeClass('hide');
                $('.lama').addClass('hide');
            }else{
                $('.baru').addClass('hide');
                $('.lama').addClass('hide');
            }
        }

    </script>
@endsection